### ISSUE TITLE
MobileNetV2 based Hourglass

### ISSUE THREAD

**Issue by tucan9389** [tucan9389/tf2-mobile-pose-estimation#30]
- working branch: `new-model/mv2_hourglass`

## Structure

<img src="https://user-images.githubusercontent.com/37643248/111898531-fa45a700-8a69-11eb-9cc7-b19d00b57e6d.png" width=500px>

## Test Points on Future

- [ ] [lightweight] Change stage (4 → 3, 2, 1)
- [ ] [improving pck] Change stage (4 → 5, 6 ,8, 16)
- [ ] [improving pck] More hourglass (1 → 2, 3, 4, 8)

## Reference

- https://github.com/edvardHua/PoseEstimationForMobile
- https://arxiv.org/abs/1603.06937

**Comment by tucan9389** [comment]
## TODO

- [ ] make it class (not a function)
